!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!  This file contains code for constructing expansions of the Sturm-Liouville
!  eigenvalues of the prolate spheroidal wave functions of order 0 as a  function
!  of bandlimit c and a parameter u related to the value of the nonoscillatory phase 
!  function at 0.
!
!  We denote by chi_n(c) the Sturm-Liouville eigenvalue of ps_n(x,c) and by
!  alpha(x, c, chi_n(c)) the nonoscillatory phase whose value approaches 0
!  as x approaches 1.  Then it can be easily verified that
!
!    alpha(x, c, chi_n(c)) = -pi/2 (n + 1).
!
!  We now can also view chi as a function of c and a new parameter eta defined
!  through the formula
!
!    alpha(0, c, chi(eta,c) ) = - pi/2 (eta+1)
!
!  This definition ensures that
!
!    alpha(0, c, chi(n,c) )  = n;
!
!  in other words, for a fixed value of c chi(eta,c) is the inverse function of
!  the map
!
!     chi --->  2/pi*alpha(0, c, chi)-1.
!
!  Each expansion holds for 
!
!     500 <= c <= 500 * 2^nc     and    eta1 < eta < eta2
!
!  with nc >=1  a user-specified constant and either eta1 and eta2 chosen such that
!
!    eta1 = 50    and   \chi(eta2, c) = c^2                                               (1)
!
!  or 
!
!    \chi(eta1,c)=c^2    and   \chi(eta2, c) = 10c^2                                      (2)
!
!  In fact, the expansions actually vary with a parameter u which varies between 0
!  and 1 and is defined via
!
!    eta = eta1 + (eta2 - eta1) u.
!
!  That is, the expansions are actually of the function
!
!    chi(eta(u),c).
!
!  The parameter u is introduced because ranges of eta (1) and (2) depend on the value of 
!  c.  This code also produces expansions of 
!
!    d/dx alpha(0, c, chi(eta(u),c) ),
!
!    (d/dx)^2 alpha(0, c, chi(eta(u),c) ), and                                            (3)
!
!    (d/dx)^3 alpha(0, c, chi(eta(u),c) )
!
!  as functions of u and c.  The structure of the expansions is the same as for
!  chi(eta(u),c).
!
!  The following subroutines should be regarded as publicly callable:
!
!    prolates_exps_one - construct expansions of chi and the functions (3) which
!      vary with u but not c; i.e., the resulting expansions hold for one fixed value
!      of c
!
!    prolates_exp_construct - construct expansions of chi(eta(u),c) and the functions
!      (3) which vary for u and c
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module prolates_exps

use utils
use chebyshev
use riccati
use linearode
use prolates
use tensor
use prolates_window

type         prolates_exp1_data
integer                       :: nints, isubst, k
double precision              :: c
double precision, allocatable :: ab(:,:),chivals(:,:),xs(:)
double precision, allocatable :: apvals(:,:),appvals(:,:),apppvals(:,:)
end type     prolates_exp1_data

contains



subroutine prolates_exps_construct(eps,irange,ic1,ic2,chebdata,isubst,nintsab,ab,nintscd,cd, &
  chicoefs,apcoefs,appcoefs,apppcoefs,eta1coefs,eta2coefs)
implicit double precision (a-h,o-z)
type(chebexps_data)                              :: chebdata
double precision                                 :: eps
integer                                          :: irange, nc
double precision, allocatable, intent(out)       :: ab(:,:), cd(:,:),chicoefs(:,:,:)
double precision, allocatable, intent(out)       :: apcoefs(:,:,:),appcoefs(:,:,:)
double precision, allocatable, intent(out)       :: apppcoefs(:,:,:)
double precision, allocatable, intent(out)       :: eta1coefs(:,:),eta2coefs(:,:)
!
!  Construct an expansion of chi(eta(u),c) for 
!
!    256*2^ic1 <= c <= 256*2^ic2                                                          (4)
!
!  and one of the ranges of etas (1) or (2).  This routine adaptively discretizes
!  chi(eta(u),c) as a function of u but uses a fixed discretization grid in the
!  c variable.
!
!  Input parameters:
!    eps - precision for the adaptive discretization procedure
!    irange - an integer parameter specifying the range of the parameter eta
!
!       irange = 1     indicates the range (1) for eta
!       irange = 2     indicates the range (2) for eta
!
!    ic1,ic2 - integer parameters speciying the range of values of c
!       as in (4)
!
!    chebdata - data structure generated by chebexps; the element k in this
!      structure is the number of Chebyshev discretization nodes per interval
!    isubst - an integer parameter specifying the transformation see 
!      prolates_window_avals -- this should almost always be set to 0
!
!  Output parameters:
!    nintsab,ab - the piecwise discretization scheme in the u variable
!    nintscd,cd - the piecwise discrization scheme in the c variable
!    chicoefs - a (k*(k+1)/2,nintsab,nintscd) array giving the Chebyshev
!      coefficients of the function on each of the discretization intervals
!    apcoefs - a (k*(k+1)/2,nintsab,nintscd) array giving the Chebyshev
!      coefficients of the first function in (3)
!    appcoefs - a (k*(k+1)/2,nintsab,nintscd) array giving the Chebyshev
!      coefficients of the second function in (3)
!    apppcoefs - a (k*(k+1)/2,nintsab,nintscd) array giving the Chebyshev
!      coefficients of the third function in (3)
!    eta1coefs - a (k,nintscd) function giving the Chebyshev expansion
!      of eta1(c)
!    eta2coefs - a (k,nintscd) function giving the Chebyshev expansion
!      of eta2(c)

!

type(c_ptr)                                      :: userptr

double precision, allocatable                    :: ab0(:,:),chivals0(:,:),apvals0(:,:)
double precision, allocatable                    :: appvals0(:,:),apppvals0(:,:),ab1(:,:)
double precision, allocatable                    :: eta1vals(:,:),eta2vals(:,:)

type(prolates_exp1_data), allocatable, target    :: exps(:,:)
double precision, allocatable                    :: utensor(:,:),vals(:,:),coefs(:)

integer                                          :: OMP_GET_MAX_THREADS

k       = chebdata%k
pi      = acos(-1.0d0)

!
!  Manually construct a discretization scheme for the "c" variable
!

!nintscd = 12
nintscd = ic2-ic1

allocate(cd(2,nintscd))
allocate(eta1vals(k,nintscd))
allocate(eta2vals(k,nintscd))
allocate(eta1coefs(k,nintscd))
allocate(eta2coefs(k,nintscd))

do intcd=1,nintscd
cd(1,intcd)   = 256 * 2d0**(ic1+intcd-1)
cd(2,intcd)   = 256 * 2d0**(ic1+intcd)
end do


!
!  Compute an expansion for each value of c
!

allocate(exps(k,nintscd))

do intcd = 1, nintscd
c0 = cd(1,intcd)
d0 = cd(2,intcd)


write (*,*) ""
write (*,"(A,D15.7,A,D15.7)") "prolates_exps: c0 = ",c0,", d0 = ",d0
write (*,"(A)") "-------------------------------------------------------------------------------"

call elapsed(t1)

!$OMP PARALLEL DEFAULT(SHARED)  PRIVATE(c,i,eta1,eta2)  NUM_THREADS(4)
!$OMP DO SCHEDULE(DYNAMIC)
do i=1,k

! build the expansion for one value of c
c = (d0-c0)/2 * chebdata%xs(i) + (c0+d0)/2

exps(i,intcd)%c      = c 
exps(i,intcd)%isubst = isubst
exps(i,intcd)%k      = k

allocate(exps(i,intcd)%xs(k))
exps(i,intcd)%xs = chebdata%xs

call prolates_exps_one(eps,irange,chebdata,c,isubst,exps(i,intcd)%nints,exps(i,intcd)%ab,       &
 exps(i,intcd)%chivals,exps(i,intcd)%apvals,exps(i,intcd)%appvals,exps(i,intcd)%apppvals,       & 
 eta1,eta2)

eta1vals(i,intcd) = eta1
eta2vals(i,intcd) = eta2

end do
!$OMP END DO
!$OMP END PARALLEL

!
!  Form the coefficient expansions for eta1 and eta2
!
eta1coefs(:,intcd) = matmul(chebdata%u,eta1vals(:,intcd))
eta2coefs(:,intcd) = matmul(chebdata%u,eta2vals(:,intcd))


call elapsed(t2)
write (*,"(A,D15.4)") "---------------------------------------------------------------- time = ",t2-t1
write (*,*) ""

end do

!
!  Form a unified discretization in the u variable
!

call elapsed(t1)
nints0 = 1
allocate(ab0(2,nints0))
ab0(1,1) = 0.0d0
ab0(2,1) = 1.0d0

do intcd = 1, nintscd
do i=1,k

userptr = c_loc(exps(i,intcd))
call chebadap2(ier,eps,nints0,ab0,prolates_window_discfun2,k,chebdata,nints1,ab1,userptr)

deallocate(ab0)
nints0 = nints1
allocate(ab0(2,nints0))
ab0 = ab1
deallocate(ab1)

end do
end do
call elapsed(t2)


!call prin2("unified time = ",t2-t1)
nintsab = nints0
allocate(ab(2,nintsab))
ab = ab0



call tensor_umatrix(k,ncoefs,utensor)

dsize = ncoefs* 8.0d0/(1024.0d0*1024.0d0)
dsize = dsize * nintsab*nintscd

! call prini("in prolates_window_exps, nintscd = ",nintscd)
! call prin2("in prolates_window_exps, cd = ",cd)

! call prini("in prolates_window_exps, nintsab = ",nintsab)
! call prin2("in prolates_window_exps, ab = ",ab)

! call prin2("in prolates_window_exps, expansion size (MB) = ",dsize)

!
!  Compute the coefficient expansions
!

allocate(vals(k,k))
allocate(chicoefs(ncoefs,nintsab,nintscd))
allocate(apcoefs(ncoefs,nintsab,nintscd))
allocate(appcoefs(ncoefs,nintsab,nintscd))
allocate(apppcoefs(ncoefs,nintsab,nintscd))

do intab=1,nintsab
a0 = ab(1,intab)
b0 = ab(2,intab)

do intcd=1,nintscd

c0 = cd(1,intcd)
d0 = cd(2,intcd)

! chi 
do i=1,k
do j=1,k

c = (d0-c0)/2 * chebdata%xs(i) + (d0+c0)/2
u = (b0-a0)/2 * chebdata%xs(j) + (b0+a0)/2

call chebpw_eval(exps(i,intcd)%nints,exps(i,intcd)%ab,k,chebdata%xs,exps(i,intcd)%chivals,u,val)
vals(j,i) = val

end do
end do
call tensor_coefs(k,utensor,vals,chicoefs(:,intab,intcd))

! apval
do i=1,k
do j=1,k

c = (d0-c0)/2 * chebdata%xs(i) + (d0+c0)/2
u = (b0-a0)/2 * chebdata%xs(j) + (b0+a0)/2

call chebpw_eval(exps(i,intcd)%nints,exps(i,intcd)%ab,k,chebdata%xs,exps(i,intcd)%apvals,u,val)
vals(j,i) = val

end do
end do
call tensor_coefs(k,utensor,vals,apcoefs(:,intab,intcd))

! appval
do i=1,k
do j=1,k

c = (d0-c0)/2 * chebdata%xs(i) + (d0+c0)/2
u = (b0-a0)/2 * chebdata%xs(j) + (b0+a0)/2

call chebpw_eval(exps(i,intcd)%nints,exps(i,intcd)%ab,k,chebdata%xs,exps(i,intcd)%appvals,u,val)
vals(j,i) = val

end do
end do
call tensor_coefs(k,utensor,vals,appcoefs(:,intab,intcd))


!apppval

do i=1,k
do j=1,k

c = (d0-c0)/2 * chebdata%xs(i) + (d0+c0)/2
u = (b0-a0)/2 * chebdata%xs(j) + (b0+a0)/2

call chebpw_eval(exps(i,intcd)%nints,exps(i,intcd)%ab,k,chebdata%xs,exps(i,intcd)%apppvals,u,val)
vals(j,i) = val

end do
end do
call tensor_coefs(k,utensor,vals,apppcoefs(:,intab,intcd))

!call prin2("chicoefs = ",chicoefs(:,intab,intcd)/chicoefs(1,intab,intcd))
!call prin2("apcoefs  = ",apcoefs(:,intab,intcd)/apcoefs(1,intab,intcd))

dtail      = 0

nn       = k+k-1+k-2
dd2      = maxval(abs(chicoefs(ncoefs-nn:ncoefs,intab,intcd)))
dd1      = maxval(abs(chicoefs(:,intab,intcd)))
dtail    = dd2/dd1

dd2      = maxval(abs(apcoefs(ncoefs-nn:ncoefs,intab,intcd)))
dd1      = maxval(abs(apcoefs(:,intab,intcd)))
dtail    = max(dtail,dd2/dd1)

write (*,"(A,D11.3,A,D11.3,A,D11.3,A,D11.3,A,D11.3)") &
  "prolates_exps: a0 = ",a0,", b0 =",b0," c0 = ",c0,", d0 = ",d0,", dtail = ", dtail


end do
end do

end subroutine


subroutine prolates_exps_one(eps,irange,chebdata,c,isubst,nints,ab,chivals, &
  apvals,appvals, apppvals,eta1,eta2)
implicit double precision (a-h,o-z)
type(chebexps_data)                              :: chebdata
double precision, allocatable, intent(out)       :: ab(:,:), chivals(:,:)
double precision, allocatable, intent(out)       :: apvals(:,:),appvals(:,:),apppvals(:,:)
!
!
!  This subroutine adaptively constructs a piecewise Chebyshev expansion of the function
!
!    f(u) = \chi(\eta(u))
!
!  where u is related to eta through the formula
!
!    eta = eta1 + (eta2 - eta1) u 
! 
!  with u varying between 0 and 1.  An expansion which holds for 
!
!    eta1 = 50 and chi(eta2) = c^2                                                        (5)
!
!  or one which holds for
!
!    chi(eta1) = c^2 and chi(eta2) = 10 c^2                                               (6)
!
!  is constructed.
!
!  Input parameters:
!    eps - precision for the adaptive discretization procedure
!
!    irange - an integer parameter specifying the range of the parameter eta
!
!       irange = 1     indicates the range (1)
!       irange = 2     indicates the range (2)
     
!    chebdata - data structure generated by chebexps; the element k in this
!      structure is the number of Chebyshev discretization nodes per interval
!    c - the (fixed) bandlimit
!    isubst - an integer parameter specifying the transformation (see
!      prolates_window.f90) --- this should almost certainly be 0
!
!  Output parameters:
!    nints - the number of intervals used to discretize \chi(\eta(u))
!    ab - a (2,nints) array specifying the discretization intervals
!    chivals - a (k,nints) array speciying the values of \chi at the
!       Chebyshev discretization nodes
!    apvals, appvals, apppvals - (k,nints) arrays specifying the values of
!      the functions in (3) at the Chebyshev discretization nodes
!
!    

type(prolates_qfun_data), pointer     :: qdata
type(c_ptr)                           :: userptr
double complex                        :: clambda
double precision, allocatable         :: coefsps(:),coefsqs(:),ab0(:,:),coefs(:)
double precision, allocatable         :: avals0(:,:),ab1(:,:),avals(:,:)
double precision, allocatable         :: apvals0(:,:),appvals0(:,:),apppvals0(:,:)

integer :: omp_get_num_threads, omp_get_max_threads


call elapsed(time1)

allocate(qdata)
userptr = c_loc(qdata)


pi       = acos(-1.0d0)
maxiters = 200
k        = chebdata%k
ntail    = .25d0*k

if (irange .eq. 1) then

n1       = 100
call prolates_integer(c,n1,chi1,clambda,ncoefs,coefsps,coefsqs)
chi2     = c**2

elseif (irange .eq. 2) then

chi1         = c**2
chi2         = 10*c**2

endif

a            = chi1
b            = chi2

! call prind("chi1 = ",chi1)
! call prind("chi2 = ",chi2)


!
!  Adaptively discretize the function f(chi) = -2/pi * alpha(0,c,chi) -1 over the interval
!  a < chi < b
!

qdata%c      = c
qdata%isubst = isubst
qdata%eps    = eps

i1 = omp_get_num_threads()
i2 = omp_get_max_threads()
d1 = i1
d2 = i2

nthreads = ceiling(d2/d1)
call  chebadap_threaded(ier,eps,a,b,prolates_window_discfun,k,chebdata,nints0,ab0,userptr,nthreads)

if (ier .ne. 0) then
call prini("after chebadap, ier = ",ier)
stop
endif

!call prini("in prolates_exp_one, nints0 = ",nints0)
!call prin2("in prolates_exp_one, ab0    = ",ab0)


!
!  Evaluate the aforementioned function at every discretization node; also,
!  discretize \alpha'(0,chi), alpha''(0,chi), and alpha'''(0,chi)
!

allocate(avals0(k,nints0),coefs(k))
allocate(apvals0(k,nints0),appvals0(k,nints0),apppvals0(k,nints0))

!$OMP PARALLEL DEFAULT(SHARED) PRIVATE(int,a0,b0,i,chi,aval,apval,appval,apppval)
!$OMP DO
do int=1,nints0
a0  = ab0(1,int)
b0  = ab0(2,int)

do i=1,k
chi = (b0-a0)/2 * chebdata%xs(i) + (a0+b0)/2

call prolates_window_avals(c,chi,isubst,aval,apval,appval,apppval)

avals0(i,int)     = -2/pi*aval-1
apvals0(i,int)    = apval
appvals0(i,int)   = appval
apppvals0(i,int)  = apppval

end do
end do
!$OMP END DO
!$OMP END PARALLEL


!
!  Check the accuracy of the forward expansion by computing the
!  ratio of the L^2 norm of trailing coefficients to the L^2 norm of
!  all the coefficients
!

dtail1 = 0

!$OMP PARALLEL DEFAULT(SHARED) PRIVATE(int,coefs,dd1,dd2)
!$OMP DO
do int=1,nints0
coefs = matmul(chebdata%u,avals0(:,int))

dd1   = maxval(abs(coefs))
dd2   = maxval(abs(coefs(k-ntail+1:k)))
dd      = dd2/dd1
!$OMP ATOMIC 
dtail1  = max(dd,dtail1)


coefs = matmul(chebdata%u,apvals0(:,int))
dd1   = maxval(abs(coefs))
dd2   = maxval(abs(coefs(k-ntail+1:k)))
dd      = dd2/dd1
!$OMP ATOMIC 
dtail1  = max(dd,dtail1)

end do
!$OMP END DO
!$OMP END PARALLEL


!
!  Form the inverse function
!

nints = nints0
allocate(ab(2,nints),chivals(k,nints))

do int=1,nints0
a0 = ab0(1,int)
b0 = ab0(2,int)

call chebpw_eval(nints0,ab0,k,chebdata%xs,avals0,a0,a)
call chebpw_eval(nints0,ab0,k,chebdata%xs,avals0,b0,b)

ab(1,int) = a
ab(2,int) = b

end do


!
!  Use bisection to compute the inverse function
!

!$OMP PARALLEL DEFAULT(SHARED) PRIVATE(int,a,b,a0,b0,i,x,t,t1,t2,iter,val)
!$OMP DO
do int = 1,nints

a   = ab(1,int)
b   = ab(2,int)

a0  = ab0(1,int)
b0  = ab0(2,int)


do i = 1,k
x   = (b-a)/2*chebdata%xs(i) + (b+a)/2

if (i .eq. 1) then
t = a0
elseif ( i .eq. k) then
t = b0
else


t1 = a0
t2 = b0

do iter=1,maxiters

t = (t1+t2)/2

call chebpw_eval(nints0,ab0,k,chebdata%xs,avals0,t,val)

if (abs(x-val) .lt. eps) exit
if (x .lt. val) then
t1 = t1
t2 = t
else
t1 = t
t2 = t2
endif

end do
endif 


chivals(i,int) = t

end do
end do
!$OMP END DO
!$OMP END PARALLEL


!
!  Pull back the function to the interval (0,1)
!
eta1        = ab(1,1)
eta2        = ab(2,nints)

ab          = (ab - eta1)/(eta2-eta1)
ab(1,1)     = 0
ab(2,nints) = 1


!
!  Form the expansion of  alpha'(chi(u)) alpha''(chi(u)), and alpha'''(chi(u))
!

allocate(apvals(k,nints))
allocate(appvals(k,nints))
allocate(apppvals(k,nints))


!$OMP PARALLEL DEFAULT(SHARED) PRIVATE(int,a0,b0,i,chi,apval,appval,apppval)
!$OMP DO
do int=1,nints
a0  = ab(1,int)
b0  = ab(2,int)
do i=1,k
chi = chivals(i,int)
call chebpw_eval(nints0,ab0,k,chebdata%xs,apvals0,chi,apval)
call chebpw_eval(nints0,ab0,k,chebdata%xs,appvals0,chi,appval)
call chebpw_eval(nints0,ab0,k,chebdata%xs,apppvals0,chi,apppval)

apvals(i,int)    = apval
appvals(i,int)   = appval
apppvals(i,int)  = apppval

end do
end do
!$OMP END DO
!$OMP END PARALLEL

!
!  Check the accuracy of the expansions 
!

dtail2 = 0
!$OMP PARALLEL DEFAULT(shared) PRIVATE(int,coefs,dd1,dd2,dd)
!$OMP DO
do int=1,nints

coefs    = matmul(chebdata%u,chivals(:,int))
dd1      = maxval(abs(coefs))
dd2      = maxval(abs(coefs(k-ntail+1:k)))
dd       = dd2/dd1
!$OMP ATOMIC
dtail2  = max(dd,dtail2)

coefs    = matmul(chebdata%u,apvals(:,int))
dd1      = maxval(abs(coefs))
dd2      = maxval(abs(coefs(k-ntail+1:k)))
dd       = dd2/dd1
!$OMP ATOMIC
dtail2  = max(dd,dtail2)

end do
!$OMP END DO
!$OMP END PARALLEL

call elapsed(time2)
dtime = time2-time1
!
!  Succintly display some information to the user  
!

write (*,"(A,D15.6,A,D15.6,A,D15.6,A,D15.6,A,I3.3)") &
  "prolates_window_exps1: c =  ",c,", dtail1 = ",dtail1,",  dtail2 = ",dtail2, &
  ", time = ",dtime,", nints = ",nints

write (13,"(A,D15.6,A,D15.6,A,D15.6,A,D15.6,A,I3.3)") &
  "prolates_window_exps1: c =  ",c,", dtail1 = ",dtail1,",  dtail2 = ",dtail2, &
  ", time = ",dtime,", nints = ",nints


end subroutine



subroutine prolates_window_discfun(t,val1,val2,userptr)
implicit double precision (a-h,o-z)
double precision, intent(in)          :: t
double precision, intent(out)         :: val1,val2
type(c_ptr)                           :: userptr
type(prolates_qfun_data), pointer     :: qdata

data pi / 3.14159265358979323846264338327950288d0 /

call c_f_pointer(userptr,qdata)

c      = qdata%c
chi    = t
isubst = qdata%isubst
eps    = qdata%eps

call prolates_window_avals(c,chi,isubst,aval,apval,appval,apppval)

val1 = aval
val2 = apval

end subroutine


subroutine prolates_window_discfun2(t,val1,val2,userptr)
implicit double precision (a-h,o-z)
double precision, intent(in)          :: t
double precision, intent(out)         :: val1,val2
type(c_ptr)                           :: userptr
type(prolates_exp1_data), pointer     :: exp

call c_f_pointer(userptr,exp)
call chebpw_eval(exp%nints,exp%ab,exp%k,exp%xs,exp%chivals,t,val)
call chebpw_eval(exp%nints,exp%ab,exp%k,exp%xs,exp%apvals,t,apval)
val1 = val
val2 = apval


end subroutine




end module
